import time
import re
from urllib.parse import quote
from .account_manager import ACCOUNT_MAP

def generate_html_card(ctx, data, index):
    urgency = data.get('urgency', 'low').lower()
    if urgency not in ['low', 'medium', 'high']: urgency = 'low'
    
    urg_class = f"urg-{urgency}"
    urg_label_map = {'low': 'נמוכה', 'medium': 'בינונית', 'high': 'גבוהה'}
    urg_label = urg_label_map.get(urgency, 'נמוכה')
    
    action_req = data.get('action_required', False)
    action_label = "נדרשת פעולה" if action_req else "אין פעולה נדרשת"
    
    uid = f"{index}_{int(time.time())}"
    
    # Enrichment (Already done in run_workflow, but fetching here for display)
    active_account_id = data.get('active_member_account_id', '')
    account_info = ACCOUNT_MAP.get(active_account_id, {})
    
    if not active_account_id:
         # Double check if not passed (should not happen with new flow)
         active_account_id = data.get('extracted_account_id', '')
         account_info = ACCOUNT_MAP.get(active_account_id, {})

    customer = account_info.get('customer', '')
    account_name = account_info.get('accountName', '')
    poc_name = account_info.get('pocName', '')
    ops_email = account_info.get('operationsEmail', '')
    
    # Extract dates from bodyText for export
    body_text = data.get('bodyText', '')
    start_date = ''
    end_date = ''
    
    # Try to extract Start Date
    start_match = re.search(r'Start Date:\s*(\d{4}-\d{2}-\d{2})', body_text)
    if start_match:
        start_date = start_match.group(1)
    
    # Try to extract Last Detected Date or End Date
    end_match = re.search(r'(?:Last Detected Date|End Date):\s*(\d{4}-\d{2}-\d{2})', body_text)
    if end_match:
        end_date = end_match.group(1)
    elif start_date:
        end_date = start_date  # Fallback to start if no end found
    
    # Extract service for export (First occurrence only - each anomaly has one service)
    service_match = re.search(r'AWS Service:\s*([^\n]+)', body_text)
    services = service_match.group(1).strip() if service_match else ''
    
    # Extract Region (First occurrence)
    region_match = re.search(r'Region:\s*([^\n]+)', body_text)
    region = region_match.group(1).strip() if region_match else ''
    
    # Extract Usage Type (First occurrence)
    usage_match = re.search(r'Usage Type:\s*([^\n]+)', body_text)
    usage_type = usage_match.group(1).strip() if usage_match else ''
    
    # Meta lines
    meta_parts = []
    # Shorten fromName - extract only part before @ if it's an email
    from_name = data.get('fromName', '')
    from_address = data.get('fromAddress', '')
    if '@' in from_address:
        display_name = from_address.split('@')[0]  # Just the username part
    else:
        display_name = from_name
    
    meta_parts.append(f"מאת: {display_name}")
    if data.get('date'):
        meta_parts.append(f"תאריך: <span dir='ltr'>{data.get('date')}</span>")
    
    if customer: meta_parts.append(f"לקוח: {customer}")
    
    # Enhanced Account Info in Meta
    acc_display = f"{active_account_id}"
    if account_name:
        acc_display += f" ({account_name})"
    if active_account_id:
        meta_parts.append(f"חשבון: <strong>{acc_display}</strong>")
        
    # Total Impact
    total_impact = data.get('total_impact_usd', 'Unknown')
    if total_impact and total_impact != 'Unknown':
         meta_parts.append(f"<div style='margin-top:8px; font-size:1.1em; color:#d32f2f; font-weight:800; border:1px solid #ef4444; display:inline-block; padding:2px 8px; border-radius:4px; background:#fef2f2;'>Total Impact: {total_impact}</div>")
    
    meta_html = "<br />".join(meta_parts)
    
    # Compose Links
    
    # Create custom subject: "Abra - anomaly alert <Account Name> (<Account ID>)"
    custom_subject = f"Abra - anomaly alert {account_name} ({active_account_id})"
    
    # CC recipients
    cc_emails = "eyal.stoler@abra-it.com,Shaked.Gofer@abra-it.com,Snir.Gridish@abra-it.com"
    
    # Email Bodies are now fully generated by LLM based on strict templates
    team_body = f"{data.get('team_message_he', '')}\\n\\nהפעולה הבאה (HE):\\n{data.get('next_action_he', '')}"
    client_he_body = f"{data.get('client_message_he', '')}"
    client_en_body = f"{data.get('client_message_en', '')}"
    
    gmail_team = f"mailto:?subject={quote(custom_subject)}&cc={quote(cc_emails)}&body={quote(team_body)}"
    gmail_client_he = f"mailto:{ops_email}?subject={quote(custom_subject)}&cc={quote(cc_emails)}&body={quote(client_he_body)}"
    gmail_client_en = f"mailto:{ops_email}?subject={quote(custom_subject)}&cc={quote(cc_emails)}&body={quote(client_en_body)}"
    
    # Determine badge info
    msg_family = data.get('message_family', 'cost_anomaly')
    if msg_family == 'budget_notification':
        badge_text = "Budget"
        badge_style = "background-color: #fb4934; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.7em; vertical-align: middle; margin-right: 8px; display:inline-block;"
    elif msg_family == 'ri_utilization_alert':
        badge_text = "RI Alert"
        badge_style = "background-color: #b16286; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.7em; vertical-align: middle; margin-right: 8px; display:inline-block;"
    elif msg_family == 'free_tier':
        badge_text = "Free Tier"
        badge_style = "background-color: #00bcd4; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.7em; vertical-align: middle; margin-right: 8px; display:inline-block;"
    else:
        badge_text = "Anomaly"
        badge_style = "background-color: #16a765; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.7em; vertical-align: middle; margin-right: 8px; display:inline-block;"

    card_html = f"""
    <div class="card" data-urgency="{urgency}">
        <div class="urg-container">
            <span class="badge {urg_class}">דחיפות: {urg_label}</span>
        </div>
        
        <div class="row">
            <div>
                <div class="subject">
                    <span style="{badge_style}">{badge_text}</span>
                    {custom_subject}
                </div>
                <div class="meta">{meta_html}</div>
            </div>
        </div>
        
        <div class="summary-box he" style="background:#f0f9ff; border:1px solid #bae6fd; border-radius:8px; padding:12px; margin:10px 0;">
            <div style="font-weight:600; color:#0369a1; margin-bottom:5px;">📋 תקציר:</div>
            <div style="color:#1e3a5f; line-height:1.5;">{data.get('summary_he', 'לא נמצא תקציר')}</div>
        </div>
        
        <div class="he">
            <div class="action-status">{action_label}</div>
            
            <div class="button-group">
                <button class="btn" onclick="toggleSection('{uid}-an', this)">פרטים (HE)</button>
                <button class="btn" onclick="toggleSection('{uid}-tm', this)">הודעה לצוות</button>
                <button class="btn" onclick="toggleSection('{uid}-ch', this)">לקוח (HE)</button>
                <button class="btn" onclick="toggleSection('{uid}-ce', this)">Client (EN)</button>
                <a class="btn" href="/api/email/{data.get('id')}" target="_blank" style="background:#f3f4f6; color:#374151; border-color:#d1d5db;">👁️ המייל המקורי</a>
                {f'<a class="btn" href="{data.get("console_link")}" target="_blank">פתח בקונסולה</a>' if data.get('console_link') else ''}
                <button class="btn" onclick="exportAnomaly('{customer}', '{account_name}', '{active_account_id}', '{start_date}', '{end_date}', '{total_impact}', '{services.replace("'", "\\'")}', '{region}', '{usage_type.replace("'", "\\'")}')" style="background:#fef3c7; color:#92400e; border-color:#fde68a;">📊 ייצא לקובץ מעקב</button>
            </div>
        </div>
        
        <div id="{uid}-an" class="section he" style="display:none;">
            <div class="section-title">פרטים מלאים:</div>
            <pre>{data.get('anomalies_he', '')}</pre>
        </div>

        
        <div id="{uid}-tm" class="section he" style="display:none;">
            <div class="section-title">הודעה לצוות:</div>
            <pre>{data.get('team_message_he', '')}</pre>
            <div class="next-action"><strong>הפעולה הבאה:</strong> {data.get('next_action_he', '')}</div>
            <div style="margin-top:10px;">
                <a class="btn" href="{gmail_team}" style="background:#e0f2fe; color:#0369a1; border-color:#bae6fd;">📧 פתח טיוטה לצוות</a>
            </div>
        </div>
        
        <div id="{uid}-ch" class="section he" style="display:none;">
            <div class="section-title">לקוח (עברית):</div>
            <pre>{data.get('client_message_he', '')}</pre>
            <div style="margin-top:10px;">
                <a class="btn" href="{gmail_client_he}" style="background:#dcfce7; color:#15803d; border-color:#86efac;">📧 פתח טיוטה ללקוח (HE)</a>
            </div>
        </div>
        
        <div id="{uid}-ce" class="section ltr" style="display:none;">
            <div class="section-title">Client (EN):</div>
            <pre>{data.get('client_message_en', '')}</pre>
             <div class="next-action"><strong>Next action:</strong> {data.get('next_action_en', '')}</div>
            <div style="margin-top:10px;">
                <a class="btn" href="{gmail_client_en}" style="background:#dcfce7; color:#15803d; border-color:#86efac;">📧 Open Client Draft (EN)</a>
            </div>
        </div>
    </div>
    """
    return card_html
